### ISSUE TITLE
Error in adding single variables in the basket

### ISSUE THREAD

**Issue by Federico321** [ddionrails/ddionrails#574] opened 2019-06-07 11:21 UTC
### Subject of the issue
Create a customized basket of variables

### Expected behaviour
I want to create a customized basket of variable on paneldata.org. When I go to on SOEP-Core, I select topics and I search in the folder the single demand to which I am interested.

### Actual behaviour
I get an error when I add the single variable in my basket. Oppositely, I don't get an error adding a whole folder.

### Steps to reproduce
![Immagine](https://user-images.githubusercontent.com/51479928/59100687-20e32e00-8927-11e9-88e1-8ec648c12d27.png)

**Comment by afuetterer** [comment] 2019-06-07 12:55
Thanks for reporting this.

**Comment by Federico321** [comment] 2019-06-07 17:23
I have also created a basket adding several folders for a machine learning analysis, but I got another error:
![Immagine2](https://user-images.githubusercontent.com/51479928/59121952-b5ff1a80-8959-11e9-9b88-560907994e76.png)

**Comment by hansendx** [comment] 2019-06-14 15:31
Thak you again for the input.
We have located the problem and it is related to #428.

A while back there was a change in the underlying data and the preprocessing of it.
After this, the names of the data columns did no longer fit what the preprocessor expected.
This in turn lead to all topics being assigned the value "Concept_None" which does not exist.
With these non existing Concepts the associated variables and questions could not be found.
And since they could not be found, they could also not be added to the basket.

The underlying data problem was fixed in a [commit](https://github.com/paneldata/soep-core/commit/5b6ddb30206b33ff75317a83b247885fe1196f0c) in the https://github.com/paneldata/soep-core repository.
It will take some time to include the corrected data but this should no longer be a problem after the update of the data.
I will close the issue, when the data has benn updatet.

**Comment by Federico321** [comment] 2019-06-17 09:55
Thanks a lot for the answer. I would feel to suggest to allow also to select a single year in the basket. I mean when hundreds of variables have been added, it could be nice select directly the year upon to that matrix and not drop each variable individually. Thanks again and have a good day.
Federico Lenzi
________________________________
Da: hansendx <notifications@github.com>
Inviato: venerdì 14 giugno 2019 17:31:23
A: ddionrails/ddionrails
Cc: Federico Lenzi - federico.lenzi3@studio.unibo.it; Author
Oggetto: Re: [ddionrails/ddionrails] Error in adding single variables in the basket (#574)


Thak you again for the input.
We have located the problem and it is related to #428<https://github.com/ddionrails/ddionrails/issues/428>.

A while back there was a change in the underlying data and the preprocessing of it.
After this, the names of the data columns did no longer fit what the preprocessor expected.
This in turn lead to all topics being assigned the value "Concept_None" which does not exist.
With these non existing Concepts the associated variables and questions could not be found.
And since they could not be found, they could also not be added to the basket.

The underlying data problem was fixed in a commit<https://github.com/paneldata/soep-core/commit/5b6ddb30206b33ff75317a83b247885fe1196f0c> in the https://github.com/paneldata/soep-core repository.
It will take some time to include the corrected data but this should no longer be a problem after the update of the data.
I will close the issue, when the data has benn updatet.

**Comment by hansendx** [comment] 2019-06-17 15:48
The problem is fixed on the liveserver paneldata.org. (see Pictures)
I will now close this issue.

@Federico321 thank you for the input. It would help us, if you would add feature requests, like the changes to the basket, as separate issues here, since it simplifies tracking them. I will add that changes to the basket (in its current state) are relatively complicated. The whole basket might need an overhaul in the near future.

Have an nice day.

![Screenshot from 2019-06-17 17-24-34](https://user-images.githubusercontent.com/20108516/59617290-5a394c00-9126-11e9-8f64-0f8f52f95ddb.png)
![Screenshot from 2019-06-17 17-32-20](https://user-images.githubusercontent.com/20108516/59617295-5d343c80-9126-11e9-96a9-977063a6cd69.png)

**Closed by hansendx** 2019-06-17 15:48 UTC
Labels: Type: Bug

**Comment by Federico321** [comment] 2019-06-17 18:08
Thanks a lot!
________________________________
Da: hansendx <notifications@github.com>
Inviato: lunedì 17 giugno 2019 17:51:44
A: ddionrails/ddionrails
Cc: Federico Lenzi - federico.lenzi3@studio.unibo.it; Mention
Oggetto: Re: [ddionrails/ddionrails] Error in adding single variables in the basket (#574)


The problem is fixed on the liveserver paneldata.org. (see Pictures)
I will now close this issue.

@Federico321<https://github.com/Federico321> thank you for the input. It would help us, if you would add feature requests, like the changes to the basket, as separate issues here, since it simplifies tracking them. I will add that changes to the basket (in its current state) are relatively complicated. The whole basket might need an overhaul in the near future.

Have an nice day.

[Screenshot from 2019-06-17 17-24-34]<https://user-images.githubusercontent.com/20108516/59617290-5a394c00-9126-11e9-8f64-0f8f52f95ddb.png>
[Screenshot from 2019-06-17 17-32-20]<https://user-images.githubusercontent.com/20108516/59617295-5d343c80-9126-11e9-96a9-977063a6cd69.png>
